import { CaseStudy } from "./types";

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: "byte-burger",
    businessName: "Byte Burger",
    businessType: "Restaurant",
    story:
      "Byte Burger is a popular local burger joint that's been around for 10 years. They recently decided to go online, but their nephew built the website and it's... not great. The navigation is confusing, there's no appetizing hero image, the menu section is just a wall of text, and the footer has broken links. They need YOUR team to redesign their site!",
    brokenSections: [
      {
        id: "slot-header",
        label: "Header / Navigation",
        assignedTo: null,
        turnOrder: 0,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-hero",
        label: "Hero Section",
        assignedTo: null,
        turnOrder: 0,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-features",
        label: "Menu / Features",
        assignedTo: null,
        turnOrder: 1,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-testimonials",
        label: "Reviews / Testimonials",
        assignedTo: null,
        turnOrder: 1,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-cta",
        label: "Call to Action",
        assignedTo: null,
        turnOrder: 2,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-footer",
        label: "Footer",
        assignedTo: null,
        turnOrder: 2,
        placedComponent: null,
        status: "empty",
      },
    ],
    idealCategories: {
      "slot-header": ["headers"],
      "slot-hero": ["hero_sections"],
      "slot-features": ["feature_sections", "bento_grids"],
      "slot-testimonials": ["testimonials"],
      "slot-cta": ["cta_sections"],
      "slot-footer": ["footers"],
    },
    scoringCriteria: [
      "Clear navigation with restaurant name visible",
      "Appetizing hero image or visual",
      "Menu items are easy to read and organized",
      "Customer reviews build trust",
      "Clear call-to-action (Order Now, Visit Us)",
      "Footer has contact info and hours",
    ],
  },
  {
    id: "technova",
    businessName: "TechNova",
    businessType: "SaaS Startup",
    story:
      "TechNova builds project management software for small teams. Their current site was thrown together during a hackathon—there's no clear value proposition, the features section is a wall of text, there's no pricing information, and no obvious way to sign up. Help them convert visitors into customers!",
    brokenSections: [
      {
        id: "slot-header",
        label: "Header / Navigation",
        assignedTo: null,
        turnOrder: 0,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-hero",
        label: "Hero Section",
        assignedTo: null,
        turnOrder: 0,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-features",
        label: "Features Section",
        assignedTo: null,
        turnOrder: 1,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-pricing",
        label: "Pricing Section",
        assignedTo: null,
        turnOrder: 1,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-cta",
        label: "Call to Action",
        assignedTo: null,
        turnOrder: 2,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-footer",
        label: "Footer",
        assignedTo: null,
        turnOrder: 2,
        placedComponent: null,
        status: "empty",
      },
    ],
    idealCategories: {
      "slot-header": ["headers"],
      "slot-hero": ["hero_sections"],
      "slot-features": ["feature_sections", "bento_grids"],
      "slot-pricing": ["pricing_sections"],
      "slot-cta": ["cta_sections"],
      "slot-footer": ["footers"],
    },
    scoringCriteria: [
      "Clear value proposition in hero",
      "Features are scannable, not walls of text",
      "Pricing is transparent and easy to compare",
      "Strong CTA (Start Free Trial, Sign Up)",
      "Professional, trustworthy appearance",
      "Footer includes legal and contact links",
    ],
  },
  {
    id: "greenleaf-studio",
    businessName: "GreenLeaf Studio",
    businessType: "Design Agency",
    story:
      "GreenLeaf Studio is a creative design agency that ironically has a terrible website. The layout is cluttered, there's no portfolio showcase, the team section is missing, and the footer is ugly. They say 'the cobbler's children have no shoes.' Prove them wrong!",
    brokenSections: [
      {
        id: "slot-header",
        label: "Header / Navigation",
        assignedTo: null,
        turnOrder: 0,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-hero",
        label: "Hero Section",
        assignedTo: null,
        turnOrder: 0,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-content",
        label: "Portfolio / Content",
        assignedTo: null,
        turnOrder: 1,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-team",
        label: "Team Section",
        assignedTo: null,
        turnOrder: 1,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-contact",
        label: "Contact Section",
        assignedTo: null,
        turnOrder: 2,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-footer",
        label: "Footer",
        assignedTo: null,
        turnOrder: 2,
        placedComponent: null,
        status: "empty",
      },
    ],
    idealCategories: {
      "slot-header": ["headers"],
      "slot-hero": ["hero_sections"],
      "slot-content": ["content_sections", "blog_sections", "bento_grids"],
      "slot-team": ["team_sections"],
      "slot-contact": ["contact_sections"],
      "slot-footer": ["footers"],
    },
    scoringCriteria: [
      "Clean, modern navigation",
      "Visually striking hero that shows creativity",
      "Portfolio/work showcase is organized",
      "Team section builds personal connection",
      "Easy to contact the agency",
      "Footer is clean and professional",
    ],
  },
  {
    id: "fittrack",
    businessName: "FitTrack",
    businessType: "Fitness App",
    story:
      "FitTrack is a fitness tracking app that helps people reach their health goals. Their landing page is a mess—no social proof, confusing pricing tiers, and no clear download button. They're losing potential users every day. Create a landing page that makes people want to download the app!",
    brokenSections: [
      {
        id: "slot-header",
        label: "Header / Navigation",
        assignedTo: null,
        turnOrder: 0,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-hero",
        label: "Hero Section",
        assignedTo: null,
        turnOrder: 0,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-features",
        label: "App Features",
        assignedTo: null,
        turnOrder: 1,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-testimonials",
        label: "Testimonials",
        assignedTo: null,
        turnOrder: 1,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-stats",
        label: "Stats / Social Proof",
        assignedTo: null,
        turnOrder: 2,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-footer",
        label: "Footer",
        assignedTo: null,
        turnOrder: 2,
        placedComponent: null,
        status: "empty",
      },
    ],
    idealCategories: {
      "slot-header": ["headers"],
      "slot-hero": ["hero_sections"],
      "slot-features": ["feature_sections"],
      "slot-testimonials": ["testimonials"],
      "slot-stats": ["stats_sections", "logo_clouds"],
      "slot-footer": ["footers"],
    },
    scoringCriteria: [
      "Clear app branding in header",
      "Hero makes you want to download the app",
      "Features show app benefits clearly",
      "Testimonials feel authentic and motivating",
      "Stats build credibility (users, downloads, etc.)",
      "Footer has download links and social media",
    ],
  },
  {
    id: "pawpals",
    businessName: "PawPals",
    businessType: "Pet Adoption Nonprofit",
    story:
      "PawPals is a local animal shelter that helps find forever homes for rescue pets. Their website hasn't been updated in years—there's no about section explaining their mission, the team page is missing, and their adoption stats aren't shown. Help them tell their story and save more lives!",
    brokenSections: [
      {
        id: "slot-header",
        label: "Header / Navigation",
        assignedTo: null,
        turnOrder: 0,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-hero",
        label: "Hero Section",
        assignedTo: null,
        turnOrder: 0,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-about",
        label: "About / Mission",
        assignedTo: null,
        turnOrder: 1,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-stats",
        label: "Adoption Stats",
        assignedTo: null,
        turnOrder: 1,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-cta",
        label: "Donate / Adopt CTA",
        assignedTo: null,
        turnOrder: 2,
        placedComponent: null,
        status: "empty",
      },
      {
        id: "slot-footer",
        label: "Footer",
        assignedTo: null,
        turnOrder: 2,
        placedComponent: null,
        status: "empty",
      },
    ],
    idealCategories: {
      "slot-header": ["headers"],
      "slot-hero": ["hero_sections"],
      "slot-about": ["content_sections", "header_sections"],
      "slot-stats": ["stats_sections"],
      "slot-cta": ["cta_sections", "newsletter_sections"],
      "slot-footer": ["footers"],
    },
    scoringCriteria: [
      "Warm, inviting navigation with shelter name",
      "Emotional hero that connects with visitors",
      "Clear mission statement and story",
      "Impactful stats (animals saved, adopted, etc.)",
      "Strong CTA to donate or adopt",
      "Footer with address, hours, and social links",
    ],
  },
];
