// ==========================================
// Component Registry for DesignDash
// Auto-generated from Tailwind component library
// ==========================================

import { ComponentEntry, ComponentCategory } from "./types";

export const COMPONENT_REGISTRY: Record<ComponentCategory, ComponentEntry[]> = {
  // ── Headers ──────────────────────────────────────────────
  headers: [
    {
      id: "headers-constrained",
      name: "Constrained",
      category: "headers",
      preview: "/Tailwind/tailwind/headers/constrained.png",
      jsx: "/Tailwind/tailwind/headers/constrained.jsx",
    },
    {
      id: "headers-full_width",
      name: "Full Width",
      category: "headers",
      preview: "/Tailwind/tailwind/headers/full_width.png",
      jsx: "/Tailwind/tailwind/headers/full_width.jsx",
    },
    {
      id: "headers-on_brand_background",
      name: "On Brand Background",
      category: "headers",
      preview: "/Tailwind/tailwind/headers/on_brand_background.png",
      jsx: "/Tailwind/tailwind/headers/on_brand_background.jsx",
    },
    {
      id: "headers-with_call_to_action",
      name: "With Call To Action",
      category: "headers",
      preview: "/Tailwind/tailwind/headers/with_call_to_action.png",
      jsx: "/Tailwind/tailwind/headers/with_call_to_action.jsx",
    },
    {
      id: "headers-with_centered_logo",
      name: "With Centered Logo",
      category: "headers",
      preview: "/Tailwind/tailwind/headers/with_centered_logo.png",
      jsx: "/Tailwind/tailwind/headers/with_centered_logo.jsx",
    },
    {
      id: "headers-with_full_width_flyout_menu",
      name: "With Full Width Flyout Menu",
      category: "headers",
      preview: "/Tailwind/tailwind/headers/with_full_width_flyout_menu.png",
      jsx: "/Tailwind/tailwind/headers/with_full_width_flyout_menu.jsx",
    },
    {
      id: "headers-with_icons_in_mobile_menu",
      name: "With Icons In Mobile Menu",
      category: "headers",
      preview: "/Tailwind/tailwind/headers/with_icons_in_mobile_menu.png",
      jsx: "/Tailwind/tailwind/headers/with_icons_in_mobile_menu.jsx",
    },
    {
      id: "headers-with_left_aligned_nav",
      name: "With Left Aligned Nav",
      category: "headers",
      preview: "/Tailwind/tailwind/headers/with_left_aligned_nav.png",
      jsx: "/Tailwind/tailwind/headers/with_left_aligned_nav.jsx",
    },
    {
      id: "headers-with_multiple_flyout_menus",
      name: "With Multiple Flyout Menus",
      category: "headers",
      preview: "/Tailwind/tailwind/headers/with_multiple_flyout_menus.png",
      jsx: "/Tailwind/tailwind/headers/with_multiple_flyout_menus.jsx",
    },
    {
      id: "headers-with_right_aligned_nav",
      name: "With Right Aligned Nav",
      category: "headers",
      preview: "/Tailwind/tailwind/headers/with_right_aligned_nav.png",
      jsx: "/Tailwind/tailwind/headers/with_right_aligned_nav.jsx",
    },
    {
      id: "headers-with_stacked_flyout_menu",
      name: "With Stacked Flyout Menu",
      category: "headers",
      preview: "/Tailwind/tailwind/headers/with_stacked_flyout_menu.png",
      jsx: "/Tailwind/tailwind/headers/with_stacked_flyout_menu.jsx",
    },
  ],

  // ── Hero Sections ────────────────────────────────────────
  hero_sections: [
    {
      id: "hero_sections-simple_centered",
      name: "Simple Centered",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/simple_centered.png",
      jsx: "/Tailwind/tailwind/hero_sections/simple_centered_system.jsx",
    },
    {
      id: "hero_sections-simple_centered_with_background_image",
      name: "Simple Centered With Background Image",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/simple_centered_with_background_image.png",
      jsx: "/Tailwind/tailwind/hero_sections/simple_centered_with_background_image_system.jsx",
    },
    {
      id: "hero_sections-split_with_bordered_screenshot",
      name: "Split With Bordered Screenshot",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/split_with_bordered_screenshot.png",
      jsx: "/Tailwind/tailwind/hero_sections/split_with_bordered_screenshot_system.jsx",
    },
    {
      id: "hero_sections-split_with_code_example",
      name: "Split With Code Example",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/split_with_code_example.png",
      jsx: "/Tailwind/tailwind/hero_sections/split_with_code_example_system.jsx",
    },
    {
      id: "hero_sections-split_with_image",
      name: "Split With Image",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/split_with_image.png",
      jsx: "/Tailwind/tailwind/hero_sections/split_with_image_system.jsx",
    },
    {
      id: "hero_sections-split_with_screenshot",
      name: "Split With Screenshot",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/split_with_screenshot.png",
      jsx: "/Tailwind/tailwind/hero_sections/split_with_screenshot_system.jsx",
    },
    {
      id: "hero_sections-with_angled_image_on_right",
      name: "With Angled Image On Right",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/with_angled_image_on_right.png",
      jsx: "/Tailwind/tailwind/hero_sections/with_angled_image_on_right_system.jsx",
    },
    {
      id: "hero_sections-with_app_screenshot",
      name: "With App Screenshot",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/with_app_screenshot.png",
      jsx: "/Tailwind/tailwind/hero_sections/with_app_screenshot_system.jsx",
    },
    {
      id: "hero_sections-with_bordered_app_screenshot",
      name: "With Bordered App Screenshot",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/with_bordered_app_screenshot.png",
      jsx: "/Tailwind/tailwind/hero_sections/with_bordered_app_screenshot_system.jsx",
    },
    {
      id: "hero_sections-with_image_tiles",
      name: "With Image Tiles",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/with_image_tiles.png",
      jsx: "/Tailwind/tailwind/hero_sections/with_image_tiles_system.jsx",
    },
    {
      id: "hero_sections-with_offset_image",
      name: "With Offset Image",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/with_offset_image.png",
      jsx: "/Tailwind/tailwind/hero_sections/with_offset_image_system.jsx",
    },
    {
      id: "hero_sections-with_phone_mockup",
      name: "With Phone Mockup",
      category: "hero_sections",
      preview: "/Tailwind/tailwind/hero_sections/with_phone_mockup.png",
      jsx: "/Tailwind/tailwind/hero_sections/with_phone_mockup_system.jsx",
    },
  ],

  // ── Feature Sections ─────────────────────────────────────
  feature_sections: [
    {
      id: "feature_sections-centered_2x2_grid",
      name: "Centered 2x2 Grid",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/centered_2x2_grid.png",
      jsx: "/Tailwind/tailwind/feature_sections/centered_2x2_grid.jsx",
    },
    {
      id: "feature_sections-contained_in_panel",
      name: "Contained In Panel",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/contained_in_panel.png",
      jsx: "/Tailwind/tailwind/feature_sections/contained_in_panel.jsx",
    },
    {
      id: "feature_sections-offset_2x2_grid",
      name: "Offset 2x2 Grid",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/offset_2x2_grid.png",
      jsx: "/Tailwind/tailwind/feature_sections/offset_2x2_grid.jsx",
    },
    {
      id: "feature_sections-offset_with_feature_list",
      name: "Offset With Feature List",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/offset_with_feature_list.png",
      jsx: "/Tailwind/tailwind/feature_sections/offset_with_feature_list.jsx",
    },
    {
      id: "feature_sections-simple_3x2_grid",
      name: "Simple 3x2 Grid",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/simple_3x2_grid.png",
      jsx: "/Tailwind/tailwind/feature_sections/simple_3x2_grid.jsx",
    },
    {
      id: "feature_sections-simple_three_column_with_large_icons",
      name: "Simple Three Column With Large Icons",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/simple_three_column_with_large_icons.png",
      jsx: "/Tailwind/tailwind/feature_sections/simple_three_column_with_large_icons.jsx",
    },
    {
      id: "feature_sections-simple_three_column_with_small_icons",
      name: "Simple Three Column With Small Icons",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/simple_three_column_with_small_icons.png",
      jsx: "/Tailwind/tailwind/feature_sections/simple_three_column_with_small_icons.jsx",
    },
    {
      id: "feature_sections-simple",
      name: "Simple",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/simple.png",
      jsx: "/Tailwind/tailwind/feature_sections/simple.jsx",
    },
    {
      id: "feature_sections-with_code_example_panel",
      name: "With Code Example Panel",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/with_code_example_panel.png",
      jsx: "/Tailwind/tailwind/feature_sections/with_code_example_panel.jsx",
    },
    {
      id: "feature_sections-with_large_bordered_screenshot",
      name: "With Large Bordered Screenshot",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/with_large_bordered_screenshot.png",
      jsx: "/Tailwind/tailwind/feature_sections/with_large_bordered_screenshot.jsx",
    },
    {
      id: "feature_sections-with_large_screenshot",
      name: "With Large Screenshot",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/with_large_screenshot.png",
      jsx: "/Tailwind/tailwind/feature_sections/with_large_screenshot.jsx",
    },
    {
      id: "feature_sections-with_product_screenshot_on_left",
      name: "With Product Screenshot On Left",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/with_product_screenshot_on_left.png",
      jsx: "/Tailwind/tailwind/feature_sections/with_product_screenshot_on_left.jsx",
    },
    {
      id: "feature_sections-with_product_screenshot_panel",
      name: "With Product Screenshot Panel",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/with_product_screenshot_panel.png",
      jsx: "/Tailwind/tailwind/feature_sections/with_product_screenshot_panel.jsx",
    },
    {
      id: "feature_sections-with_product_screenshot",
      name: "With Product Screenshot",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/with_product_screenshot.png",
      jsx: "/Tailwind/tailwind/feature_sections/with_product_screenshot.jsx",
    },
    {
      id: "feature_sections-with_testimonial",
      name: "With Testimonial",
      category: "feature_sections",
      preview: "/Tailwind/tailwind/feature_sections/with_testimonial.png",
      jsx: "/Tailwind/tailwind/feature_sections/with_testimonial.jsx",
    },
  ],

  // ── Content Sections ─────────────────────────────────────
  content_sections: [
    {
      id: "content_sections-centered",
      name: "Centered",
      category: "content_sections",
      preview: "/Tailwind/tailwind/content_sections/centered.png",
      jsx: "/Tailwind/tailwind/content_sections/centered.jsx",
    },
    {
      id: "content_sections-split_with_image",
      name: "Split With Image",
      category: "content_sections",
      preview: "/Tailwind/tailwind/content_sections/split_with_image.png",
      jsx: "/Tailwind/tailwind/content_sections/split_with_image.jsx",
    },
    {
      id: "content_sections-two_columns_with_screenshot",
      name: "Two Columns With Screenshot",
      category: "content_sections",
      preview: "/Tailwind/tailwind/content_sections/two_columns_with_screenshot.png",
      jsx: "/Tailwind/tailwind/content_sections/two_columns_with_screenshot.jsx",
    },
    {
      id: "content_sections-with_image_tiles",
      name: "With Image Tiles",
      category: "content_sections",
      preview: "/Tailwind/tailwind/content_sections/with_image_tiles.png",
      jsx: "/Tailwind/tailwind/content_sections/with_image_tiles.jsx",
    },
    {
      id: "content_sections-with_sticky_product_screenshot",
      name: "With Sticky Product Screenshot",
      category: "content_sections",
      preview: "/Tailwind/tailwind/content_sections/with_sticky_product_screenshot.png",
      jsx: "/Tailwind/tailwind/content_sections/with_sticky_product_screenshot.jsx",
    },
    {
      id: "content_sections-with_testimonial_and_stats",
      name: "With Testimonial And Stats",
      category: "content_sections",
      preview: "/Tailwind/tailwind/content_sections/with_testimonial_and_stats.png",
      jsx: "/Tailwind/tailwind/content_sections/with_testimonial_and_stats.jsx",
    },
    {
      id: "content_sections-with_testimonial",
      name: "With Testimonial",
      category: "content_sections",
      preview: "/Tailwind/tailwind/content_sections/with_testimonial.png",
      jsx: "/Tailwind/tailwind/content_sections/with_testimonial.jsx",
    },
  ],

  // ── CTA Sections ─────────────────────────────────────────
  cta_sections: [
    {
      id: "cta_sections-centered_on_dark_panel",
      name: "Centered On Dark Panel",
      category: "cta_sections",
      preview: "/Tailwind/tailwind/cta_sections/centered_on_dark_panel.png",
      jsx: "/Tailwind/tailwind/cta_sections/centered_on_dark_panel.jsx",
    },
    {
      id: "cta_sections-dark_panel_with_app_screenshot",
      name: "Dark Panel With App Screenshot",
      category: "cta_sections",
      preview: "/Tailwind/tailwind/cta_sections/dark_panel_with_app_screenshot.png",
      jsx: "/Tailwind/tailwind/cta_sections/dark_panel_with_app_screenshot.jsx",
    },
    {
      id: "cta_sections-simple_centered_on_brand",
      name: "Simple Centered On Brand",
      category: "cta_sections",
      preview: "/Tailwind/tailwind/cta_sections/simple_centered_on_brand.png",
      jsx: "/Tailwind/tailwind/cta_sections/simple_centered_on_brand.jsx",
    },
    {
      id: "cta_sections-simple_centered_with_gradient",
      name: "Simple Centered With Gradient",
      category: "cta_sections",
      preview: "/Tailwind/tailwind/cta_sections/simple_centered_with_gradient.png",
      jsx: "/Tailwind/tailwind/cta_sections/simple_centered_with_gradient.jsx",
    },
    {
      id: "cta_sections-simple_centered",
      name: "Simple Centered",
      category: "cta_sections",
      preview: "/Tailwind/tailwind/cta_sections/simple_centered.png",
      jsx: "/Tailwind/tailwind/cta_sections/simple_centered.jsx",
    },
    {
      id: "cta_sections-simple_justified_on_subtle_brand",
      name: "Simple Justified On Subtle Brand",
      category: "cta_sections",
      preview: "/Tailwind/tailwind/cta_sections/simple_justified_on_subtle_brand.png",
      jsx: "/Tailwind/tailwind/cta_sections/simple_justified_on_subtle_brand.jsx",
    },
    {
      id: "cta_sections-simple_justified",
      name: "Simple Justified",
      category: "cta_sections",
      preview: "/Tailwind/tailwind/cta_sections/simple_justified.png",
      jsx: "/Tailwind/tailwind/cta_sections/simple_justified.jsx",
    },
    {
      id: "cta_sections-simple_stacked",
      name: "Simple Stacked",
      category: "cta_sections",
      preview: "/Tailwind/tailwind/cta_sections/simple_stacked.png",
      jsx: "/Tailwind/tailwind/cta_sections/simple_stacked.jsx",
    },
    {
      id: "cta_sections-split_with_image",
      name: "Split With Image",
      category: "cta_sections",
      preview: "/Tailwind/tailwind/cta_sections/split_with_image.png",
      jsx: "/Tailwind/tailwind/cta_sections/split_with_image.jsx",
    },
    {
      id: "cta_sections-two_columns_with_photo",
      name: "Two Columns With Photo",
      category: "cta_sections",
      preview: "/Tailwind/tailwind/cta_sections/two_columns_with_photo.png",
      jsx: "/Tailwind/tailwind/cta_sections/two_columns_with_photo.jsx",
    },
    {
      id: "cta_sections-with_image_tiles",
      name: "With Image Tiles",
      category: "cta_sections",
      preview: "/Tailwind/tailwind/cta_sections/with_image_tiles.png",
      jsx: "/Tailwind/tailwind/cta_sections/with_image_tiles.jsx",
    },
  ],

  // ── Pricing Sections ─────────────────────────────────────
  pricing_sections: [
    {
      id: "pricing_sections-four_tiers_with_toggle",
      name: "Four Tiers With Toggle",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/four_tiers_with_toggle.png",
      jsx: "/Tailwind/tailwind/pricing_sections/four_tiers_with_toggle.jsx",
    },
    {
      id: "pricing_sections-single_price_with_details",
      name: "Single Price With Details",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/single_price_with_details.png",
      jsx: "/Tailwind/tailwind/pricing_sections/single_price_with_details.jsx",
    },
    {
      id: "pricing_sections-three_tiers_with_dividers",
      name: "Three Tiers With Dividers",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/three_tiers_with_dividers.png",
      jsx: "/Tailwind/tailwind/pricing_sections/three_tiers_with_dividers.jsx",
    },
    {
      id: "pricing_sections-three_tiers_with_emphasized_tier",
      name: "Three Tiers With Emphasized Tier",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/three_tiers_with_emphasized_tier.png",
      jsx: "/Tailwind/tailwind/pricing_sections/three_tiers_with_emphasized_tier.jsx",
    },
    {
      id: "pricing_sections-three_tiers_with_feature_comparison",
      name: "Three Tiers With Feature Comparison",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/three_tiers_with_feature_comparison.png",
      jsx: "/Tailwind/tailwind/pricing_sections/three_tiers_with_feature_comparison.jsx",
    },
    {
      id: "pricing_sections-three_tiers_with_logos_and_feature_comparison",
      name: "Three Tiers With Logos And Feature Comparison",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/three_tiers_with_logos_and_feature_comparison.png",
      jsx: "/Tailwind/tailwind/pricing_sections/three_tiers_with_logos_and_feature_comparison.jsx",
    },
    {
      id: "pricing_sections-three_tiers_with_toggle",
      name: "Three Tiers With Toggle",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/three_tiers_with_toggle.png",
      jsx: "/Tailwind/tailwind/pricing_sections/three_tiers_with_toggle.jsx",
    },
    {
      id: "pricing_sections-three_tiers",
      name: "Three Tiers",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/three_tiers.png",
      jsx: "/Tailwind/tailwind/pricing_sections/three_tiers.jsx",
    },
    {
      id: "pricing_sections-two_tiers_with_emphasized_left_tier",
      name: "Two Tiers With Emphasized Left Tier",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/two_tiers_with_emphasized_left_tier.png",
      jsx: "/Tailwind/tailwind/pricing_sections/two_tiers_with_emphasized_left_tier.jsx",
    },
    {
      id: "pricing_sections-two_tiers_with_emphasized_right_tier",
      name: "Two Tiers With Emphasized Right Tier",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/two_tiers_with_emphasized_right_tier.png",
      jsx: "/Tailwind/tailwind/pricing_sections/two_tiers_with_emphasized_right_tier.jsx",
    },
    {
      id: "pricing_sections-two_tiers_with_extra_tier",
      name: "Two Tiers With Extra Tier",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/two_tiers_with_extra_tier.png",
      jsx: "/Tailwind/tailwind/pricing_sections/two_tiers_with_extra_tier.jsx",
    },
    {
      id: "pricing_sections-with_comparison_table",
      name: "With Comparison Table",
      category: "pricing_sections",
      preview: "/Tailwind/tailwind/pricing_sections/with_comparison_table.png",
      jsx: "/Tailwind/tailwind/pricing_sections/with_comparison_table.jsx",
    },
  ],

  // ── Testimonials ─────────────────────────────────────────
  testimonials: [
    {
      id: "testimonials-grid",
      name: "Grid",
      category: "testimonials",
      preview: "/Tailwind/tailwind/testimonials/grid.png",
      jsx: "/Tailwind/tailwind/testimonials/grid.jsx",
    },
    {
      id: "testimonials-side_by_side",
      name: "Side By Side",
      category: "testimonials",
      preview: "/Tailwind/tailwind/testimonials/side_by_side.png",
      jsx: "/Tailwind/tailwind/testimonials/side_by_side.jsx",
    },
    {
      id: "testimonials-simple_centered",
      name: "Simple Centered",
      category: "testimonials",
      preview: "/Tailwind/tailwind/testimonials/simple_centered.png",
      jsx: "/Tailwind/tailwind/testimonials/simple_centered.jsx",
    },
    {
      id: "testimonials-subtle_grid",
      name: "Subtle Grid",
      category: "testimonials",
      preview: "/Tailwind/tailwind/testimonials/subtle_grid.png",
      jsx: "/Tailwind/tailwind/testimonials/subtle_grid.jsx",
    },
    {
      id: "testimonials-with_background_image",
      name: "With Background Image",
      category: "testimonials",
      preview: "/Tailwind/tailwind/testimonials/with_background_image.png",
      jsx: "/Tailwind/tailwind/testimonials/with_background_image.jsx",
    },
    {
      id: "testimonials-with_large_avatar",
      name: "With Large Avatar",
      category: "testimonials",
      preview: "/Tailwind/tailwind/testimonials/with_large_avatar.png",
      jsx: "/Tailwind/tailwind/testimonials/with_large_avatar.jsx",
    },
    {
      id: "testimonials-with_overlapping_image",
      name: "With Overlapping Image",
      category: "testimonials",
      preview: "/Tailwind/tailwind/testimonials/with_overlapping_image.png",
      jsx: "/Tailwind/tailwind/testimonials/with_overlapping_image.jsx",
    },
    {
      id: "testimonials-with_star_rating",
      name: "With Star Rating",
      category: "testimonials",
      preview: "/Tailwind/tailwind/testimonials/with_star_rating.png",
      jsx: "/Tailwind/tailwind/testimonials/with_star_rating.jsx",
    },
  ],

  // ── Team Sections ────────────────────────────────────────
  team_sections: [
    {
      id: "team_sections-full_width_with_vertical_images",
      name: "Full Width With Vertical Images",
      category: "team_sections",
      preview: "/Tailwind/tailwind/team_sections/full_width_with_vertical_images.png",
      jsx: "/Tailwind/tailwind/team_sections/full_width_with_vertical_images.jsx",
    },
    {
      id: "team_sections-grid_with_large_round_images",
      name: "Grid With Large Round Images",
      category: "team_sections",
      preview: "/Tailwind/tailwind/team_sections/grid_with_large_round_images.png",
      jsx: "/Tailwind/tailwind/team_sections/grid_with_large_round_images.jsx",
    },
    {
      id: "team_sections-grid_with_round_images",
      name: "Grid With Round Images",
      category: "team_sections",
      preview: "/Tailwind/tailwind/team_sections/grid_with_round_images.png",
      jsx: "/Tailwind/tailwind/team_sections/grid_with_round_images.jsx",
    },
    {
      id: "team_sections-large_grid_with_cards",
      name: "Large Grid With Cards",
      category: "team_sections",
      preview: "/Tailwind/tailwind/team_sections/large_grid_with_cards.png",
      jsx: "/Tailwind/tailwind/team_sections/large_grid_with_cards.jsx",
    },
    {
      id: "team_sections-with_image_and_short_paragraph",
      name: "With Image And Short Paragraph",
      category: "team_sections",
      preview: "/Tailwind/tailwind/team_sections/with_image_and_short_paragraph.png",
      jsx: "/Tailwind/tailwind/team_sections/with_image_and_short_paragraph.jsx",
    },
    {
      id: "team_sections-with_large_images",
      name: "With Large Images",
      category: "team_sections",
      preview: "/Tailwind/tailwind/team_sections/with_large_images.png",
      jsx: "/Tailwind/tailwind/team_sections/with_large_images.jsx",
    },
    {
      id: "team_sections-with_medium_images",
      name: "With Medium Images",
      category: "team_sections",
      preview: "/Tailwind/tailwind/team_sections/with_medium_images.png",
      jsx: "/Tailwind/tailwind/team_sections/with_medium_images.jsx",
    },
    {
      id: "team_sections-with_small_images",
      name: "With Small Images",
      category: "team_sections",
      preview: "/Tailwind/tailwind/team_sections/with_small_images.png",
      jsx: "/Tailwind/tailwind/team_sections/with_small_images.jsx",
    },
    {
      id: "team_sections-with_vertical_images",
      name: "With Vertical Images",
      category: "team_sections",
      preview: "/Tailwind/tailwind/team_sections/with_vertical_images.png",
      jsx: "/Tailwind/tailwind/team_sections/with_vertical_images.jsx",
    },
  ],

  // ── Stats Sections ───────────────────────────────────────
  stats_sections: [
    {
      id: "stats_sections-simple_grid",
      name: "Simple Grid",
      category: "stats_sections",
      preview: "/Tailwind/tailwind/stats_sections/simple_grid.png",
      jsx: "/Tailwind/tailwind/stats_sections/simple_grid.jsx",
    },
    {
      id: "stats_sections-simple",
      name: "Simple",
      category: "stats_sections",
      preview: "/Tailwind/tailwind/stats_sections/simple.png",
      jsx: "/Tailwind/tailwind/stats_sections/simple.jsx",
    },
    {
      id: "stats_sections-split_with_image",
      name: "Split With Image",
      category: "stats_sections",
      preview: "/Tailwind/tailwind/stats_sections/split_with_image.png",
      jsx: "/Tailwind/tailwind/stats_sections/split_with_image.jsx",
    },
    {
      id: "stats_sections-stepped",
      name: "Stepped",
      category: "stats_sections",
      preview: "/Tailwind/tailwind/stats_sections/stepped.png",
      jsx: "/Tailwind/tailwind/stats_sections/stepped.jsx",
    },
    {
      id: "stats_sections-timeline",
      name: "Timeline",
      category: "stats_sections",
      preview: "/Tailwind/tailwind/stats_sections/timeline.png",
      jsx: "/Tailwind/tailwind/stats_sections/timeline.jsx",
    },
    {
      id: "stats_sections-with_background_image",
      name: "With Background Image",
      category: "stats_sections",
      preview: "/Tailwind/tailwind/stats_sections/with_background_image.png",
      jsx: "/Tailwind/tailwind/stats_sections/with_background_image.jsx",
    },
    {
      id: "stats_sections-with_description",
      name: "With Description",
      category: "stats_sections",
      preview: "/Tailwind/tailwind/stats_sections/with_description.png",
      jsx: "/Tailwind/tailwind/stats_sections/with_description.jsx",
    },
    {
      id: "stats_sections-with_two_column_description",
      name: "With Two Column Description",
      category: "stats_sections",
      preview: "/Tailwind/tailwind/stats_sections/with_two_column_description.png",
      jsx: "/Tailwind/tailwind/stats_sections/with_two_column_description.jsx",
    },
  ],

  // ── Contact Sections ─────────────────────────────────────
  contact_sections: [
    {
      id: "contact_sections-centered",
      name: "Centered",
      category: "contact_sections",
      preview: "/Tailwind/tailwind/contact_sections/centered.png",
      jsx: "/Tailwind/tailwind/contact_sections/centered.jsx",
    },
    {
      id: "contact_sections-side_by_side_grid",
      name: "Side By Side Grid",
      category: "contact_sections",
      preview: "/Tailwind/tailwind/contact_sections/side_by_side_grid.png",
      jsx: "/Tailwind/tailwind/contact_sections/side_by_side_grid.jsx",
    },
    {
      id: "contact_sections-simple_centered",
      name: "Simple Centered",
      category: "contact_sections",
      preview: "/Tailwind/tailwind/contact_sections/simple_centered.png",
      jsx: "/Tailwind/tailwind/contact_sections/simple_centered.jsx",
    },
    {
      id: "contact_sections-simple_four_column",
      name: "Simple Four Column",
      category: "contact_sections",
      preview: "/Tailwind/tailwind/contact_sections/simple_four_column.png",
      jsx: "/Tailwind/tailwind/contact_sections/simple_four_column.jsx",
    },
    {
      id: "contact_sections-split_with_image",
      name: "Split With Image",
      category: "contact_sections",
      preview: "/Tailwind/tailwind/contact_sections/split_with_image.png",
      jsx: "/Tailwind/tailwind/contact_sections/split_with_image.jsx",
    },
    {
      id: "contact_sections-split_with_pattern",
      name: "Split With Pattern",
      category: "contact_sections",
      preview: "/Tailwind/tailwind/contact_sections/split_with_pattern.png",
      jsx: "/Tailwind/tailwind/contact_sections/split_with_pattern.jsx",
    },
    {
      id: "contact_sections-with_testimonial",
      name: "With Testimonial",
      category: "contact_sections",
      preview: "/Tailwind/tailwind/contact_sections/with_testimonial.png",
      jsx: "/Tailwind/tailwind/contact_sections/with_testimonial.jsx",
    },
  ],

  // ── Newsletter Sections ──────────────────────────────────
  newsletter_sections: [
    {
      id: "newsletter_sections-centered_card",
      name: "Centered Card",
      category: "newsletter_sections",
      preview: "/Tailwind/tailwind/newsletter_sections/centered_card.png",
      jsx: "/Tailwind/tailwind/newsletter_sections/centered_card.jsx",
    },
    {
      id: "newsletter_sections-side_by_side_on_card",
      name: "Side By Side On Card",
      category: "newsletter_sections",
      preview: "/Tailwind/tailwind/newsletter_sections/side_by_side_on_card.png",
      jsx: "/Tailwind/tailwind/newsletter_sections/side_by_side_on_card.jsx",
    },
    {
      id: "newsletter_sections-side_by_side_with_details",
      name: "Side By Side With Details",
      category: "newsletter_sections",
      preview: "/Tailwind/tailwind/newsletter_sections/side_by_side_with_details.png",
      jsx: "/Tailwind/tailwind/newsletter_sections/side_by_side_with_details.jsx",
    },
    {
      id: "newsletter_sections-simple_side_by_side_on_brand",
      name: "Simple Side By Side On Brand",
      category: "newsletter_sections",
      preview: "/Tailwind/tailwind/newsletter_sections/simple_side_by_side_on_brand.png",
      jsx: "/Tailwind/tailwind/newsletter_sections/simple_side_by_side_on_brand.jsx",
    },
    {
      id: "newsletter_sections-simple_side_by_side",
      name: "Simple Side By Side",
      category: "newsletter_sections",
      preview: "/Tailwind/tailwind/newsletter_sections/simple_side_by_side.png",
      jsx: "/Tailwind/tailwind/newsletter_sections/simple_side_by_side.jsx",
    },
    {
      id: "newsletter_sections-simple_stacked",
      name: "Simple Stacked",
      category: "newsletter_sections",
      preview: "/Tailwind/tailwind/newsletter_sections/simple_stacked.png",
      jsx: "/Tailwind/tailwind/newsletter_sections/simple_stacked.jsx",
    },
  ],

  // ── Blog Sections ────────────────────────────────────────
  blog_sections: [
    {
      id: "blog_sections-single_column_with_images",
      name: "Single Column With Images",
      category: "blog_sections",
      preview: "/Tailwind/tailwind/blog_sections/single_column_with_images.png",
      jsx: "/Tailwind/tailwind/blog_sections/single_column_with_images.jsx",
    },
    {
      id: "blog_sections-single_column",
      name: "Single Column",
      category: "blog_sections",
      preview: "/Tailwind/tailwind/blog_sections/single_column.png",
      jsx: "/Tailwind/tailwind/blog_sections/single_column.jsx",
    },
    {
      id: "blog_sections-three_column_with_background_images",
      name: "Three Column With Background Images",
      category: "blog_sections",
      preview: "/Tailwind/tailwind/blog_sections/three_column_with_background_images.png",
      jsx: "/Tailwind/tailwind/blog_sections/three_column_with_background_images.jsx",
    },
    {
      id: "blog_sections-three_column_with_images",
      name: "Three Column With Images",
      category: "blog_sections",
      preview: "/Tailwind/tailwind/blog_sections/three_column_with_images.png",
      jsx: "/Tailwind/tailwind/blog_sections/three_column_with_images.jsx",
    },
    {
      id: "blog_sections-three_column",
      name: "Three Column",
      category: "blog_sections",
      preview: "/Tailwind/tailwind/blog_sections/three_column.png",
      jsx: "/Tailwind/tailwind/blog_sections/three_column.jsx",
    },
    {
      id: "blog_sections-with_featured_post",
      name: "With Featured Post",
      category: "blog_sections",
      preview: "/Tailwind/tailwind/blog_sections/with_featured_post.png",
      jsx: "/Tailwind/tailwind/blog_sections/with_featured_post.jsx",
    },
    {
      id: "blog_sections-with_photo_and_list",
      name: "With Photo And List",
      category: "blog_sections",
      preview: "/Tailwind/tailwind/blog_sections/with_photo_and_list.png",
      jsx: "/Tailwind/tailwind/blog_sections/with_photo_and_list.jsx",
    },
  ],

  // ── Footers ──────────────────────────────────────────────
  footers: [
    {
      id: "footers-four_column_simple",
      name: "Four Column Simple",
      category: "footers",
      preview: "/Tailwind/tailwind/footers/four_column_simple.png",
      jsx: "/Tailwind/tailwind/footers/four_column_simple.jsx",
    },
    {
      id: "footers-four_column_with_call_to_action",
      name: "Four Column With Call To Action",
      category: "footers",
      preview: "/Tailwind/tailwind/footers/four_column_with_call_to_action.png",
      jsx: "/Tailwind/tailwind/footers/four_column_with_call_to_action.jsx",
    },
    {
      id: "footers-four_column_with_company_mission",
      name: "Four Column With Company Mission",
      category: "footers",
      preview: "/Tailwind/tailwind/footers/four_column_with_company_mission.png",
      jsx: "/Tailwind/tailwind/footers/four_column_with_company_mission.jsx",
    },
    {
      id: "footers-four_column_with_newsletter_below",
      name: "Four Column With Newsletter Below",
      category: "footers",
      preview: "/Tailwind/tailwind/footers/four_column_with_newsletter_below.png",
      jsx: "/Tailwind/tailwind/footers/four_column_with_newsletter_below.jsx",
    },
    {
      id: "footers-four_column_with_newsletter",
      name: "Four Column With Newsletter",
      category: "footers",
      preview: "/Tailwind/tailwind/footers/four_column_with_newsletter.png",
      jsx: "/Tailwind/tailwind/footers/four_column_with_newsletter.jsx",
    },
    {
      id: "footers-simple_centered",
      name: "Simple Centered",
      category: "footers",
      preview: "/Tailwind/tailwind/footers/simple_centered.png",
      jsx: "/Tailwind/tailwind/footers/simple_centered.jsx",
    },
    {
      id: "footers-simple_with_social_links",
      name: "Simple With Social Links",
      category: "footers",
      preview: "/Tailwind/tailwind/footers/simple_with_social_links.png",
      jsx: "/Tailwind/tailwind/footers/simple_with_social_links.jsx",
    },
  ],

  // ── Logo Clouds ──────────────────────────────────────────
  logo_clouds: [
    {
      id: "logo_clouds-grid",
      name: "Grid",
      category: "logo_clouds",
      preview: "/Tailwind/tailwind/logo_clouds/grid.png",
      jsx: "/Tailwind/tailwind/logo_clouds/grid.jsx",
    },
    {
      id: "logo_clouds-simple_with_call_to_action",
      name: "Simple With Call To Action",
      category: "logo_clouds",
      preview: "/Tailwind/tailwind/logo_clouds/simple_with_call_to_action.png",
      jsx: "/Tailwind/tailwind/logo_clouds/simple_with_call_to_action.jsx",
    },
    {
      id: "logo_clouds-simple_with_heading",
      name: "Simple With Heading",
      category: "logo_clouds",
      preview: "/Tailwind/tailwind/logo_clouds/simple_with_heading.png",
      jsx: "/Tailwind/tailwind/logo_clouds/simple_with_heading.jsx",
    },
    {
      id: "logo_clouds-simple_with_left_aligned",
      name: "Simple With Left Aligned",
      category: "logo_clouds",
      preview: "/Tailwind/tailwind/logo_clouds/simple_with_left_aligned.png",
      jsx: "/Tailwind/tailwind/logo_clouds/simple_with_left_aligned.jsx",
    },
    {
      id: "logo_clouds-simple",
      name: "Simple",
      category: "logo_clouds",
      preview: "/Tailwind/tailwind/logo_clouds/simple.png",
      jsx: "/Tailwind/tailwind/logo_clouds/simple.jsx",
    },
    {
      id: "logo_clouds-split_with_logos_on_right",
      name: "Split With Logos On Right",
      category: "logo_clouds",
      preview: "/Tailwind/tailwind/logo_clouds/split_with_logos_on_right.png",
      jsx: "/Tailwind/tailwind/logo_clouds/split_with_logos_on_right.jsx",
    },
  ],

  // ── FAQs ─────────────────────────────────────────────────
  faqs: [
    {
      id: "faqs-centered_accordion",
      name: "Centered Accordion",
      category: "faqs",
      preview: "/Tailwind/tailwind/faqs/centered_accordion.png",
      jsx: "/Tailwind/tailwind/faqs/centered_accordion.jsx",
    },
    {
      id: "faqs-offset_with_supporting_text",
      name: "Offset With Supporting Text",
      category: "faqs",
      preview: "/Tailwind/tailwind/faqs/offset_with_supporting_text.png",
      jsx: "/Tailwind/tailwind/faqs/offset_with_supporting_text.jsx",
    },
    {
      id: "faqs-side_by_side",
      name: "Side By Side",
      category: "faqs",
      preview: "/Tailwind/tailwind/faqs/side_by_side.png",
      jsx: "/Tailwind/tailwind/faqs/side_by_side.jsx",
    },
    {
      id: "faqs-three_columns_with_centered_introduction",
      name: "Three Columns With Centered Introduction",
      category: "faqs",
      preview: "/Tailwind/tailwind/faqs/three_columns_with_centered_introduction.png",
      jsx: "/Tailwind/tailwind/faqs/three_columns_with_centered_introduction.jsx",
    },
    {
      id: "faqs-three_columns",
      name: "Three Columns",
      category: "faqs",
      preview: "/Tailwind/tailwind/faqs/three_columns.png",
      jsx: "/Tailwind/tailwind/faqs/three_columns.jsx",
    },
    {
      id: "faqs-two_columns_with_centered_introduction",
      name: "Two Columns With Centered Introduction",
      category: "faqs",
      preview: "/Tailwind/tailwind/faqs/two_columns_with_centered_introduction.png",
      jsx: "/Tailwind/tailwind/faqs/two_columns_with_centered_introduction.jsx",
    },
    {
      id: "faqs-two_columns",
      name: "Two Columns",
      category: "faqs",
      preview: "/Tailwind/tailwind/faqs/two_columns.png",
      jsx: "/Tailwind/tailwind/faqs/two_columns.jsx",
    },
  ],

  // ── Banners ──────────────────────────────────────────────
  banners: [
    {
      id: "banners-bottom_aligned",
      name: "Bottom Aligned",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/bottom_aligned.png",
      jsx: "/Tailwind/tailwind/banners/bottom_aligned.jsx",
    },
    {
      id: "banners-floating_at_bottom_centered",
      name: "Floating At Bottom Centered",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/floating_at_bottom_centered.png",
      jsx: "/Tailwind/tailwind/banners/floating_at_bottom_centered.jsx",
    },
    {
      id: "banners-floating_at_bottom",
      name: "Floating At Bottom",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/floating_at_bottom.png",
      jsx: "/Tailwind/tailwind/banners/floating_at_bottom.jsx",
    },
    {
      id: "banners-left_aligned",
      name: "Left Aligned",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/left_aligned.png",
      jsx: "/Tailwind/tailwind/banners/left_aligned.jsx",
    },
    {
      id: "banners-on_brand",
      name: "On Brand",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/on_brand.png",
      jsx: "/Tailwind/tailwind/banners/on_brand.jsx",
    },
    {
      id: "banners-on_dark",
      name: "On Dark",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/on_dark.png",
      jsx: "/Tailwind/tailwind/banners/on_dark.jsx",
    },
    {
      id: "banners-privacy_notice_centered",
      name: "Privacy Notice Centered",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/privacy_notice_centered.png",
      jsx: "/Tailwind/tailwind/banners/privacy_notice_centered.jsx",
    },
    {
      id: "banners-privacy_notice_full_width",
      name: "Privacy Notice Full Width",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/privacy_notice_full_width.png",
      jsx: "/Tailwind/tailwind/banners/privacy_notice_full_width.jsx",
    },
    {
      id: "banners-privacy_notice_left_aligned",
      name: "Privacy Notice Left Aligned",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/privacy_notice_left_aligned.png",
      jsx: "/Tailwind/tailwind/banners/privacy_notice_left_aligned.jsx",
    },
    {
      id: "banners-privacy_notice_right_aligned",
      name: "Privacy Notice Right Aligned",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/privacy_notice_right_aligned.png",
      jsx: "/Tailwind/tailwind/banners/privacy_notice_right_aligned.jsx",
    },
    {
      id: "banners-with_background_glow",
      name: "With Background Glow",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/with_background_glow.png",
      jsx: "/Tailwind/tailwind/banners/with_background_glow.jsx",
    },
    {
      id: "banners-with_button",
      name: "With Button",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/with_button.png",
      jsx: "/Tailwind/tailwind/banners/with_button.jsx",
    },
    {
      id: "banners-with_link",
      name: "With Link",
      category: "banners",
      preview: "/Tailwind/tailwind/banners/with_link.png",
      jsx: "/Tailwind/tailwind/banners/with_link.jsx",
    },
  ],

  // ── Bento Grids ──────────────────────────────────────────
  bento_grids: [
    {
      id: "bento_grids-three_column_bento_grid",
      name: "Three Column Bento Grid",
      category: "bento_grids",
      preview: "/Tailwind/tailwind/bento_grids/three_column_bento_grid.png",
      jsx: "/Tailwind/tailwind/bento_grids/three_column_bento_grid.jsx",
    },
    {
      id: "bento_grids-two_row_bento_grid_with_three_column_second_row",
      name: "Two Row Bento Grid With Three Column Second Row",
      category: "bento_grids",
      preview: "/Tailwind/tailwind/bento_grids/two_row_bento_grid_with_three_column_second_row.png",
      jsx: "/Tailwind/tailwind/bento_grids/two_row_bento_grid_with_three_column_second_row.jsx",
    },
    {
      id: "bento_grids-two_row_bento_grid",
      name: "Two Row Bento Grid",
      category: "bento_grids",
      preview: "/Tailwind/tailwind/bento_grids/two_row_bento_grid.png",
      jsx: "/Tailwind/tailwind/bento_grids/two_row_bento_grid.jsx",
    },
  ],

  // ── About Pages ──────────────────────────────────────────
  about_pages: [
    {
      id: "about_pages-with_image_tiles",
      name: "With Image Tiles",
      category: "about_pages",
      preview: "/Tailwind/tailwind/about_pages/with_image_tiles_1.png",
      jsx: "/Tailwind/tailwind/about_pages/with_image_tiles.jsx",
    },
    {
      id: "about_pages-with_timeline_and_stats",
      name: "With Timeline And Stats",
      category: "about_pages",
      preview: "/Tailwind/tailwind/about_pages/with_timeline_and_stats_1.png",
      jsx: "/Tailwind/tailwind/about_pages/with_timeline_and_stats.jsx",
    },
    {
      id: "about_pages-with_two_column_description",
      name: "With Two Column Description",
      category: "about_pages",
      preview: "/Tailwind/tailwind/about_pages/with_two_column_description_1.png",
      jsx: "/Tailwind/tailwind/about_pages/with_two_column_description.jsx",
    },
  ],

  // ── 404 Pages ────────────────────────────────────────────
  "404_pages": [
    {
      id: "404_pages-simple",
      name: "Simple",
      category: "404_pages",
      preview: "/Tailwind/tailwind/404_pages/simple.png",
      jsx: "/Tailwind/tailwind/404_pages/simple.jsx",
    },
    {
      id: "404_pages-split_with_image",
      name: "Split With Image",
      category: "404_pages",
      preview: "/Tailwind/tailwind/404_pages/split_with_image.png",
      jsx: "/Tailwind/tailwind/404_pages/split_with_image.jsx",
    },
    {
      id: "404_pages-with_background_image",
      name: "With Background Image",
      category: "404_pages",
      preview: "/Tailwind/tailwind/404_pages/with_background_image.png",
      jsx: "/Tailwind/tailwind/404_pages/with_background_image.jsx",
    },
    {
      id: "404_pages-with_navbar_and_footer",
      name: "With Navbar And Footer",
      category: "404_pages",
      preview: "/Tailwind/tailwind/404_pages/with_navbar_and_footer.png",
      jsx: "/Tailwind/tailwind/404_pages/with_navbar_and_footer.jsx",
    },
    {
      id: "404_pages-with_popular_pages",
      name: "With Popular Pages",
      category: "404_pages",
      preview: "/Tailwind/tailwind/404_pages/with_popular_pages.png",
      jsx: "/Tailwind/tailwind/404_pages/with_popular_pages.jsx",
    },
  ],

  // ── Flyout Menus ─────────────────────────────────────────
  flyout_menus: [
    {
      id: "flyout_menus-full_width_two_columns",
      name: "Full Width Two Columns",
      category: "flyout_menus",
      preview: "/Tailwind/tailwind/flyout_menus/full_width_two_columns.png",
      jsx: "/Tailwind/tailwind/flyout_menus/full_width_two_columns.jsx",
    },
    {
      id: "flyout_menus-full_width",
      name: "Full Width",
      category: "flyout_menus",
      preview: "/Tailwind/tailwind/flyout_menus/full_width.png",
      jsx: "/Tailwind/tailwind/flyout_menus/full_width.jsx",
    },
    {
      id: "flyout_menus-simple_with_descriptions",
      name: "Simple With Descriptions",
      category: "flyout_menus",
      preview: "/Tailwind/tailwind/flyout_menus/simple_with_descriptions.png",
      jsx: "/Tailwind/tailwind/flyout_menus/simple_with_descriptions.jsx",
    },
    {
      id: "flyout_menus-simple",
      name: "Simple",
      category: "flyout_menus",
      preview: "/Tailwind/tailwind/flyout_menus/simple.png",
      jsx: "/Tailwind/tailwind/flyout_menus/simple.jsx",
    },
    {
      id: "flyout_menus-stacked_with_footer_actions",
      name: "Stacked With Footer Actions",
      category: "flyout_menus",
      preview: "/Tailwind/tailwind/flyout_menus/stacked_with_footer_actions.png",
      jsx: "/Tailwind/tailwind/flyout_menus/stacked_with_footer_actions.jsx",
    },
    {
      id: "flyout_menus-stacked_with_footer_list",
      name: "Stacked With Footer List",
      category: "flyout_menus",
      preview: "/Tailwind/tailwind/flyout_menus/stacked_with_footer_list.png",
      jsx: "/Tailwind/tailwind/flyout_menus/stacked_with_footer_list.jsx",
    },
    {
      id: "flyout_menus-two_column",
      name: "Two Column",
      category: "flyout_menus",
      preview: "/Tailwind/tailwind/flyout_menus/two_column.png",
      jsx: "/Tailwind/tailwind/flyout_menus/two_column.jsx",
    },
  ],

  // ── Header Sections ──────────────────────────────────────
  header_sections: [
    {
      id: "header_sections-centered_with_background_image",
      name: "Centered With Background Image",
      category: "header_sections",
      preview: "/Tailwind/tailwind/header_sections/centered_with_background_image.png",
      jsx: "/Tailwind/tailwind/header_sections/centered_with_background_image.jsx",
    },
    {
      id: "header_sections-centered_with_eyebrow",
      name: "Centered With Eyebrow",
      category: "header_sections",
      preview: "/Tailwind/tailwind/header_sections/centered_with_eyebrow.png",
      jsx: "/Tailwind/tailwind/header_sections/centered_with_eyebrow.jsx",
    },
    {
      id: "header_sections-centered",
      name: "Centered",
      category: "header_sections",
      preview: "/Tailwind/tailwind/header_sections/centered.png",
      jsx: "/Tailwind/tailwind/header_sections/centered.jsx",
    },
    {
      id: "header_sections-simple_with_background_image",
      name: "Simple With Background Image",
      category: "header_sections",
      preview: "/Tailwind/tailwind/header_sections/simple_with_background_image.png",
      jsx: "/Tailwind/tailwind/header_sections/simple_with_background_image.jsx",
    },
    {
      id: "header_sections-simple_with_eyebrow",
      name: "Simple With Eyebrow",
      category: "header_sections",
      preview: "/Tailwind/tailwind/header_sections/simple_with_eyebrow.png",
      jsx: "/Tailwind/tailwind/header_sections/simple_with_eyebrow.jsx",
    },
    {
      id: "header_sections-simple",
      name: "Simple",
      category: "header_sections",
      preview: "/Tailwind/tailwind/header_sections/simple.png",
      jsx: "/Tailwind/tailwind/header_sections/simple.jsx",
    },
    {
      id: "header_sections-with_cards",
      name: "With Cards",
      category: "header_sections",
      preview: "/Tailwind/tailwind/header_sections/with_cards.png",
      jsx: "/Tailwind/tailwind/header_sections/with_cards.jsx",
    },
    {
      id: "header_sections-with_stats",
      name: "With Stats",
      category: "header_sections",
      preview: "/Tailwind/tailwind/header_sections/with_stats.png",
      jsx: "/Tailwind/tailwind/header_sections/with_stats.jsx",
    },
  ],

  // ── Landing Pages ────────────────────────────────────────
  landing_pages: [
    {
      id: "landing_pages-with_background_image_hero_and_pricing_section",
      name: "With Background Image Hero And Pricing Section",
      category: "landing_pages",
      preview: "/Tailwind/tailwind/landing_pages/with_background_image_hero_and_pricing_section_1.png",
      jsx: "/Tailwind/tailwind/landing_pages/with_background_image_hero_and_pricing_section.jsx",
    },
    {
      id: "landing_pages-with_large_screenshot_and_testimonial",
      name: "With Large Screenshot And Testimonial",
      category: "landing_pages",
      preview: "/Tailwind/tailwind/landing_pages/with_large_screenshot_and_testimonial_1.png",
      jsx: "/Tailwind/tailwind/landing_pages/with_large_screenshot_and_testimonial.jsx",
    },
    {
      id: "landing_pages-with_mobile_screenshot_and_testimonials_grid",
      name: "With Mobile Screenshot And Testimonials Grid",
      category: "landing_pages",
      preview: "/Tailwind/tailwind/landing_pages/with_mobile_screenshot_and_testimonial_grid_1.png",
      jsx: "/Tailwind/tailwind/landing_pages/with_mobile_screenshot_and_testimonials_grid.jsx",
    },
    {
      id: "landing_pages-with_screenshots_and_stats",
      name: "With Screenshots And Stats",
      category: "landing_pages",
      preview: "/Tailwind/tailwind/landing_pages/with_screenshots_and_stats_1.png",
      jsx: "/Tailwind/tailwind/landing_pages/with_screenshots_and_stats.jsx",
    },
  ],

  // ── Pricing Pages ────────────────────────────────────────
  pricing_pages: [
    {
      id: "pricing_pages-with_comparison_table",
      name: "With Comparison Table",
      category: "pricing_pages",
      preview: "/Tailwind/tailwind/pricing_pages/with_comparison_table_1.png",
      jsx: "/Tailwind/tailwind/pricing_pages/with_comparison_table.jsx",
    },
    {
      id: "pricing_pages-with_four_tiers",
      name: "With Four Tiers",
      category: "pricing_pages",
      preview: "/Tailwind/tailwind/pricing_pages/with_four_tiers_1.png",
      jsx: "/Tailwind/tailwind/pricing_pages/with_four_tiers.jsx",
    },
    {
      id: "pricing_pages-with_three_tiers_and_testimonial",
      name: "With Three Tiers And Testimonial",
      category: "pricing_pages",
      preview: "/Tailwind/tailwind/pricing_pages/with_three_tiers_and_testimonials_1.png",
      jsx: "/Tailwind/tailwind/pricing_pages/with_three_tiers_and_testimonial.jsx",
    },
  ],
};

export const ALL_COMPONENTS: ComponentEntry[] =
  Object.values(COMPONENT_REGISTRY).flat();

export function getComponentsByCategory(
  category: ComponentCategory
): ComponentEntry[] {
  return COMPONENT_REGISTRY[category] || [];
}

export function getComponentById(id: string): ComponentEntry | undefined {
  return ALL_COMPONENTS.find((c) => c.id === id);
}
